(setq el-get-user-package-directory (locate-user-emacs-file "init-el-get"))
(el-get-bundle auto-complete)
(el-get-bundle yasnippet)
(el-get-bundle iedit)
(el-get-bundle flymake-google-cpplint)
(el-get-bundle flymake-cursor)
(el-get-bundle google-c-style)
(el-get-bundle emacs-powerline)
(el-get-bundle helm)
(el-get-bundle helm-ag)
(el-get-bundle cmake-mode)
(el-get-bundle whitespace)
(el-get-bundle yaml-mode)
(el-get-bundle haskell-mode)
(el-get-bundle magit/with-editor)
(el-get-bundle magit)
(el-get-bundle git-gutter)
(el-get-bundle flyspell)
