(setq el-get-user-package-directory (locate-user-emacs-file "el-get-init"))

(el-get-bundle auto-complete)
(el-get-bundle yasnippet)
(el-get-bundle iedit)
(el-get-bundle flymake-google-cpplint)
(el-get-bundle flymake-cursor)
(el-get-bundle google-c-style)
(el-get-bundle emacs-powerline)
(el-get-bundle helm)
(el-get-bundle helm-ag)
(el-get-bundle cmake-mode)
(el-get-bundle whitespace)
(el-get-bundle git-commit-mode)
(el-get-bundle yaml-mode)
(el-get-bundle haskell-mode)
